---
- name: get the package
  sudo: no
  get_url:
    url: https://github.com/postmodern/ruby-install/archive/v{{version}}.tar.gz
    dest: ~/ruby-install-{{version}}.tar.gz
    force: no

- name: untar the package
  sudo: no
  shell: tar -xzf ~/ruby-install-{{version}}.tar.gz creates=~/ruby-install-{{version}}

- name: install
  sudo: yes
  command: make install chdir=/home/{{ansible_ssh_user}}/ruby-install-{{version}} creates=/usr/local/bin/ruby-install

- name: build {{ruby}}
  sudo: no
  shell: /usr/local/bin/ruby-install {{ruby}} creates=~/.rubies/{{ruby.replace(' ','-')}}
  when: ruby is defined
