---
- name: get the package
  sudo: no
  get_url:
    url: https://github.com/postmodern/chruby/archive/v{{version}}.tar.gz
    dest: ~/chruby-{{version}}.tar.gz
    force: no

- name: untar the package
  sudo: no
  shell: tar -xzf ~/chruby-{{version}}.tar.gz creates=~/chruby-{{version}}

- name: install
  sudo: yes
  command: make install chdir=/home/{{ansible_ssh_user}}/chruby-{{version}} creates=/usr/local/share/chruby/chruby.sh

- name: profile.d {{version}}
  sudo: yes
  lineinfile:
    dest: /etc/profile.d/chruby.sh
    line: source /usr/local/share/chruby/chruby.sh
    regexp: chruby.sh
    create: yes
    owner: root
    group: root
    mode: 0755
